### ISSUE TITLE
Include Student work example for ORGL4030

### ISSUE THREAD

**Issue by reiners** [suwebdev/ncs-michigan#103]
We forgot to include the student work example for ORGL4030 we received from Junhee back in April. We should also discuss and decide how we handle representing class work for classes that may not have a great example. 
[Team Aquarium Presentation.pptx](https://github.com/suwebdev/ncs-michigan/files/1112635/Team.Aquarium.Presentation.pptx)

**Comment by jfehrenbacher** [comment]
How would we like to display this powerpoint? Do we want to just make it downloadable via link, should I make a slideshow that cycles through it for the ORGL4030 page? What do you guys think @shawnr @reiners

**Comment by shawnr** [comment]
Won't fix.
