### ISSUE TITLE
Update Favicon in theme.

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#106]
Create favicon with square SU NCS logo.

**Comment by shawnr** [comment]
Add to child theme and notify @shawnr when ready to deploy.

**Comment by jfehrenbacher** [comment]
I've tried an SUNCS favicon as well as just an NCS favicon at 64x64. I personally think just the "NCS" looks better as a favicon, 
![favicon](https://user-images.githubusercontent.com/14934268/27887053-912d5572-6193-11e7-9a87-32d058848db4.jpg)
![favicon1](https://user-images.githubusercontent.com/14934268/27887052-912be76e-6193-11e7-815d-cac4dd7bd87b.jpg)

but we can talk about it at the next meeting.
