### ISSUE TITLE
Touch-ups on page headers

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#107]
* Web Dev header -- image has backwards letters
* Organizational Leadership -- replace image with alternate
* DICE program pages.

**Comment by jfehrenbacher** [comment]
Web Dev header fixed.

Possible ORGL header here:

http://suncs.staging.wpengine.com/programs-courses/organizational-leadership/

Other options include:

http://www.thinkstockphotos.com/image/stock-photo-business-people-meeting-corporate-digital/628219634/popup?sq=meeting/c=477/f=CPIHVX/s=Default

http://www.thinkstockphotos.com/image/stock-photo-meeting-discussion-talking-sharing-ideas/640287942/popup?sq=meeting/c=477/f=CPIHVX/s=Default

**Comment by jfehrenbacher** [comment]
The DICE header I am stumped by, but here are a bunch of options that we can look at tomorrow, and I can whip out a header during the meeting if we like any of them.

http://www.thinkstockphotos.com/image/stock-illustration-world-map-point-line-composition/625839766/popup?sq=digital%20connection/c=477/f=CPIHVX/s=Default

http://www.thinkstockphotos.com/image/stock-illustration-lines-connected-to-thinkers/637993766/popup?sq=people%20using%20technology/c=477/f=CPIHVX/p=2/s=Default

http://www.thinkstockphotos.com/image/stock-illustration-point-line-connection-from-the-head/618972830/popup?sq=digital%20connection/c=477/f=CPIHVX/s=Default

http://www.thinkstockphotos.com/image/stock-illustration-dot-sphere-effect/540199614/popup?sq=digital%20connection/c=477/f=CPIHVX/p=2/s=Default

http://www.thinkstockphotos.com/image/stock-illustration-points-lines-and-faces-form-the-shape/613882148/popup?sq=digital%20connection/c=477/f=CPIHVX/p=2/s=Default

http://www.thinkstockphotos.com/image/stock-illustration-abstract-3d-geometric-polygonal/515739028/popup?sq=digital%20connection/c=477/f=CPIHVX/p=3/s=Default

http://www.thinkstockphotos.com/image/stock-illustration-wavy-abstract-graphic-design/626777796/popup?sq=digital/c=477/f=CPIHVX/s=Default

There are also countless vector graphics like this we could use:

http://www.thinkstockphotos.com/image/stock-illustration-digital-marketing-finance-analysis/629428080/popup?sq=digital/c=477/f=CPIHVX/s=Default

http://www.thinkstockphotos.com/image/stock-illustration-business-video-marketing-content/639310112/popup?sq=digital/c=477/f=CPIHVX/s=Default

http://www.thinkstockphotos.com/image/stock-illustration-development-integrated-3d-web-icons/666782572/popup?sq=digital/c=477/f=CPIHVX/s=Default

Or we could just do people using technology like this:

http://www.thinkstockphotos.com/image/stock-photo-multiethnic-group-of-four-men-using/672213742/popup?sq=people%20using%20technology/c=477/f=CPIHVX/s=Default

http://www.thinkstockphotos.com/image/stock-photo-diversity-friends-connection-global/517938410/popup?sq=computer%20people/R|Group%20of%20people|96478|NumberOfPeople/c=477/f=CPIHVX/s=Default
