### ISSUE TITLE
Create revised logo image

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#12]
SUNCS logo image is approved, but with a change request:

Add "School of New and Continuing Studies" in small print below the large logo type. Please do not center.

**Comment by jfehrenbacher** [comment]
Here are some potential logo treatments with "School of New and Continuing Studies" added. The fifth doesn't fit in the header position, but is worth having a look at I think. Plenty more possibilities for this. If none of these are suitable let me know and I'll throw some more up here.

[LogoTreatments.pdf](https://github.com/suwebdev/ncs-michigan/files/811734/LogoTreatments.pdf)
