### ISSUE TITLE
Replace Slider on Homepage with Image and text

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#124]
Replace slider on homepage with an image that has text saying "Seattle University for Busy Adults".

**Comment by jfehrenbacher** [comment]
![homeslider](https://user-images.githubusercontent.com/14934268/28141930-9d7d2872-6713-11e7-912c-6b57c5bc047e.jpg)
![homeslider2](https://user-images.githubusercontent.com/14934268/28141932-9f4c935e-6713-11e7-9e9d-e925da5b0305.jpg)
![homeslider3](https://user-images.githubusercontent.com/14934268/28141936-a113a38a-6713-11e7-82fa-bef039635aa7.jpg)
![homeslider4](https://user-images.githubusercontent.com/14934268/28141938-a12e4ca8-6713-11e7-9146-d807b53495f1.jpg)
![homeslider5](https://user-images.githubusercontent.com/14934268/28141937-a11be16c-6713-11e7-8b90-d28275d2f85b.jpg)
