### ISSUE TITLE
Link colors

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#127]
Update link colors so hover is not so dark in Information center and other pull-down menus with dark backgrounds.

Update link colors on header menu (email and phone) so they match our theme.

Verify link colors are correct in body content, too.

**Comment by jfehrenbacher** [comment]
Changes just need to be pulled over

```
/* Styling Links */

a {
    color: #aa0000;
}

a:hover {
    color: #2c2c2b;
};

/* Styling Info Center Links so they're not so dark on hover */

a.magicmore:hover {
    color:white;
};

/* Styling buttons on hover so they're not black */

a.button.theme-skin.small:hover {
    color:#2c2c2b;
};
```
