### ISSUE TITLE
Enhance ORGL Content

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#128]
* ORGL 3010 "learn more" link from the ORGL>Careers page points to a Course page instead of a page about ORGL 3010
* On ORGL Careers page, add Sales Manager to tabbed list
* On ORGL Careers page, make list of job postings look prettier
* On ORGL Careers page use counter bar (like used on the main ORGL page)
* On ORGL main page, move up counter bar to make it more prominent.

**Comment by jfehrenbacher** [comment]
http://suncs.staging.wpengine.com/programs-courses/organizational-leadership/

**Comment by jfehrenbacher** [comment]
http://suncs.staging.wpengine.com/programs-courses/organizational-leadership/careers/
