### ISSUE TITLE
Create Information Center Content

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#13]
Create content to fill in the Information Center. For pages that are essentially indices of SU links (to seattleu.edu pages) we can use temp placeholders of "list of policy links" or whatnot in order to indicate what will go on that page. Prioritization should be given to the new content and edited content on the content pages.

[Outline in Google doc](https://docs.google.com/document/d/1jX9KiAaHCjkdHV7_2Rt4e_6A26R6FxyNjBpYZLTdW08/edit).

**Comment by reiners** [comment]
[Classification-of-Students-82-02.pdf](https://github.com/suwebdev/ncs-michigan/files/817509/Classification-of-Students-82-02.pdf)
[policyregarding-non-matriculated-class-levela8bb.pdf](https://github.com/suwebdev/ncs-michigan/files/817510/policyregarding-non-matriculated-class-levela8bb.pdf)
[NCS Website IA_Number_2.docx](https://github.com/suwebdev/ncs-michigan/files/817513/NCS.Website.IA_Number_2.docx)

**Comment by reiners** [comment]
[NCS Time Schedule.docx](https://github.com/suwebdev/ncs-michigan/files/817858/NCS.Time.Schedule.docx)

**Comment by reiners** [comment]
Links and forms to Application to gradute, tuition remission, immunization records: 
https://www.seattleu.edu/redhawk-axis/knowledge-base-articles/how-do-i-apply-to-graduate.html 
[Tuition-Remission-Application-Form.pdf](https://github.com/suwebdev/ncs-michigan/files/817931/Tuition-Remission-Application-Form.pdf) (Tuition Rem
[12-Immunization-Record.pdf](https://github.com/suwebdev/ncs-michigan/files/817937/12-Immunization-Record.pdf)
