### ISSUE TITLE
Build out Homepage

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#17]
* Build Homepage in Wordpress
 ** Top navigation
 ** Real contact info
 ** Homepage content per design comps
 ** Images/elements as needed
* Make changes to theme CSS as needed
* Make configurations to theme as needed
* Convey files, configs, and other materials to the rest of the team so the work can be previewed on everyone's development builds
* Be prepared to deploy this page during the next Sprint to our hosting solution

**Comment by reiners** [comment]
[Upcoming NCS Events .docx](https://github.com/suwebdev/ncs-michigan/files/828580/Upcoming.NCS.Events.docx)

Hi Team, I am sure Shawn sent this over to you Jack, but just in case, here is the list of upcoming events for NCS> 
Thanks :) 
Sara

**Comment by shawnr** [comment]
Looking great!
