### ISSUE TITLE
Determine Process for Delivering Work

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#18]
Figure out how to get WP configs, content, media, settings, etc. to all necessary locations.

**Comment by jfehrenbacher** [comment]
[seattleuniversityschoolofnewandcontinuingstudies.wordpress.2017-03-21.xml.zip](https://github.com/suwebdev/ncs-michigan/files/859105/seattleuniversityschoolofnewandcontinuingstudies.wordpress.2017-03-21.xml.zip)
