### ISSUE TITLE
Design Career Info pages for each program

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#20]
Using the attached content, design career info pages for each program (WATS, DICE, ORGL).

[Careers.docx](https://github.com/suwebdev/ncs-michigan/files/835025/Careers.docx)

**Comment by jfehrenbacher** [comment]
I'm currently in the middle of building out the Careers pages, and have found a very useful 'Tour' element that allows me to do the tabbed structure I was mentioned last week for the "What Kinds of Jobs Can I Find?" section. Everything's going great! 

I did want to ask, however, if we could revamp the jobs mentioned on the WATS page. As it stands now the options include Freelance Developer, In-House Developer, Web Developer/Engineer for Tech Company, and Developer for Web Studio. I think it'd be more compelling for prospective students if we mentioned jobs that aren't just being a "developer" in different settings.

I was thinking adding things like Information Architect, UI/UX Designer/Developer, that sort of thing. I figure you might have the most expertise on this sort of thing, Shawn? Any suggestions?
