### ISSUE TITLE
Begin collecting student work

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#22]
Kick off the collection of student work for the student work features we plan.

Contact WATS, ORGL, and DICE directors with some specific requirements:

* Deadline
* Details required

**Comment by reiners** [comment]
![ethics infographic_dice_emilyfix](https://cloud.githubusercontent.com/assets/25487538/24052072/695f8e5a-0af1-11e7-9392-17df8a3dd18e.png)
Infographic from DICE Ethics Class, working on getting the class number and more work samples with Students permission per Miles. 

For ORGL, Viv thought Junhee's class had the best examples, but he is out of the country in Korea at the moment, so I will have to put a pin in that until he returns.

Shawn do you have a preference for which student work you would like to showcase?
I like these:
http://portfolio.charlessipe.com/code-coach/#/
http://katietcann.com/angular-app/#/
http://marliemagic.com/1020-Final-Project/

Also as far as how we want this to look, I noticed on  Black Lives Matter: http://blacklivesmatter.com (they have the “flipcards” menu in their “guiding principles” section of the website) which I thought could be a cool way to display content by program or class.
 
And, University of Victoria’s “maker lab” page: http://maker.uvic.ca (might be a nice model to work from—we could probably do it better, I’m sure).
