### ISSUE TITLE
Collect and deliver Blog post content

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#29]
Collect and deliver post article and author info (name, bio, link, image, etc.) to use as placeholder content for building blog post style.

**Comment by reiners** [comment]
[NCS Advertorial 1_16_2016.docx](https://github.com/suwebdev/ncs-michigan/files/859435/NCS.Advertorial.1_16_2016.docx)
[BLOG_Returning to school after a break?.docx](https://github.com/suwebdev/ncs-michigan/files/859434/BLOG_Returning.to.school.after.a.break.docx)
[Trish Bio.docx](https://github.com/suwebdev/ncs-michigan/files/859441/Trish.Bio.docx)
![trish2-360x360](https://cloud.githubusercontent.com/assets/25487538/24166817/d315ba7a-0e31-11e7-8802-fdcc85aca732.jpg)
