### ISSUE TITLE
Review, revise, and enhance content for About section  -- @reiners

### ISSUE THREAD

**Issue by reiners** [suwebdev/ncs-michigan#3]

**Comment by reiners** [comment]
[NCS Website IA_Number_Landing and 1.docx](https://github.com/suwebdev/ncs-michigan/files/764597/NCS.Website.IA_Number_Landing.and.1.docx)
 
Also, Jack, you can pull a photo of your dad from SU's PhotoShelter here: [http://seattleuniversity.photoshelter.com/search?I_DSC=Fehrenbacher&_ACT=search]
and just in case you missed Yosef's email giving you access, here you go:

Your username is: fehrenb1@seattleu.edu
Password: You will need to create one. There is a “My Account” area on the top right of our site. http://seattleuniversity.photoshelter.com/

From there you can go in and start downloading. Please disregard needing a confirmation email or anything that says status pending.

**Comment by shawnr** [comment]
Closing because it's done!
