### ISSUE TITLE
Collect info to feature 3 students with work

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#33]
Gather information to feature student and work:

* Student name
* Bio
* Student Photo
* Program
* Links
* Course where work was developed
* Images/screenshots/media of work

**Comment by reiners** [comment]
I think we might want to leave out student bios and photos. It's proving challenging enough to get permission to share the work and I am not certain all students would be comfortable with that level of sharing. (just throwing it out there for discussion). :)

**DICE:** (still waiting on permission from the 3rd student)
Shawna Stewart 
Digital Rhetoric (DICE 3030)
(http://shawnastewart.weebly.com/network-public-as-catharsis.html)

Stephen Swisher
Introduction to Digital Cultures (DICE 3000)
(http://stephenjswisher.weebly.com/digital-spaces.html)

**ORGL:**
I am waiting to hear back from Junhee's students on sharing their digital posters from one of their classes. I should have work samples to share by next Friday.

**WEBDEV**
Shawn, do you have specific work samples you would like to share?
