### ISSUE TITLE
Collect Work Samples for as many courses as possible

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#35]
Send Directors a letter asking for work samples for each course:

At least one sample per course
Verify permission from students
All courses that have run (obviously don't need samples from courses that have not run yet)

**Comment by reiners** [comment]
Still waiting on ORGL.
**DICE**
History of Text Technologies
http://hilarymarieholets.weebly.com/dice-3020-blog/breviary
 
History of Text Technologies
http://emilyhistoryoftexttechfall2016.weebly.com/home/portfolio-layout-design-site-map-navigation-schematics-and-use-case
Multimodal Communication
http://jeffbigler.weebly.com/cooking-with-culture.html
Digital Storytelling
https://vimeo.com/191898249
Key Concepts in Computing
https://matthewcomputingblog.wordpress.com/2016/05/26/dice-3010-final-project-home-automation-with-beacons/

Introduction to Digital Cultures
http://jordanmcnairy.weebly.com/body-cameras.html

**Comment by reiners** [comment]
Dice 3030: http://shawnastewart.weebly.com/network-public-as-catharsis.html
Dice 3000: http://stephenjswisher.weebly.com/digital-spaces.html

**Comment by shawnr** [comment]
For courses with not as "Showy" of assignments, perhaps collect one or two assignment descriptions for each course so prospective students can have an idea of what kind of work happens in this course.

**Comment by reiners** [comment]
Spoke with Viv and Junhee. They are still waiting on permission from one student to share a group project, but they said they should have that by Monday, April 24th. I suggest we work on building this section with what we have and we can update it as stuff trickles in.
