### ISSUE TITLE
Gather material for first student feature

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#36]
Work with Shawn to gather material for a web dev student feature:

* Which student to feature first?
* Get contact info/links from Shawn
* Follow-up with student to begin process of gathering:
  * bio
  * feedback about program
  * outcomes of program for student
  * photo
  * link to employer and/or portfolio

**Comment by reiners** [comment]
Sara is interviewing Moon already for an advetorial in The Seattle Times and will be able to use her interview for a student feature. 👍

**Comment by reiners** [comment]
I can also use Luke Green! :)
