### ISSUE TITLE
Career Page Content

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#4]
Generate some new content for the careers page.

Suggested:

* List of jobs one can get after program
* List should be an attractive presentation
* List should include descriptions of what the job does and how the job fits into the industry

**Comment by shawnr** [comment]
Look into Career Coach solution in #11 to help shape the new content on the careers page.

**Comment by reiners** [comment]
Looked into EAB recommended vendor EMSI and it looks like a career coach might be something we look into university wide. Here is what Aaron from EMSI had to say "Career Coach pricing is usually based on FTE of the institution. For 10k FTE’s, it would be $15k with the standard model. If that’s not within reach, we could do a smaller “start-up” fee to get the site built and in place for you and negotiate some progressive pricing based on usage. Alternatively, we could explore cost sharing with the rest of the institution."

**Comment by reiners** [comment]
[Careers.docx](https://github.com/suwebdev/ncs-michigan/files/834987/Careers.docx)

**Comment by shawnr** [comment]
Thanks for the great content!
