### ISSUE TITLE
Research best Appointment Plugin for Wordpress

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#41]
We need an appointment plugin in Wordpress to allow students to book advising meetings.

This task requires us to figure out our own requirements (interview Suki to get those) and match them to features in the plugins.

1. Determine required information for booking an appointment
2. Determine requirements for integrating into staff calendars (e.g. producing a standard ical feed, etc.)
3. Determine the plugin that best meets our needs

**Comment by reiners** [comment]
‘Name, Student ID, Phone, Email, and Comment’ would be nice. Thanks,
 
Suki

**Comment by shawnr** [comment]
Let's focus on minimal fields (name, email, comments) and make sure we can book specific times (best to be able to make specific time available).

It's essential to have a calendar export (iCal or other) so that staff can add the appointments calendar to their calendars.

**Comment by jfehrenbacher** [comment]
https://wordpress.org/plugins/birchschedule/

I have only checked out the paid version of this, but I'll dig in to what the free version offers this week. I know Shawn also mentioned having some knowledge of an appointment plugin that might work. If you want to comment the name here, Shawn, I'll look into it further.

**Comment by shawnr** [comment]
This is the one I've used: http://appointzilla.com/

It's OK. $99/year license. Syncs to Google Calendar.

**Comment by shawnr** [comment]
Decided on Appointzilla.
