### ISSUE TITLE
Fill out all the course pages with content

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#45]
Populate courses for each course in NCS (all of the "Courses" pages from the brochure sites). Only WebDev has quarterly breakouts -- all other programs should just be listed by number. Remove the instructor info from these course pages.

**Comment by shawnr** [comment]
Work samples for **DICE**
History of Text Technologies
http://hilarymarieholets.weebly.com/dice-3020-blog/breviary
 
History of Text Technologies
http://emilyhistoryoftexttechfall2016.weebly.com/home/portfolio-layout-design-site-map-navigation-schematics-and-use-case
Multimodal Communication
http://jeffbigler.weebly.com/cooking-with-culture.html
Digital Storytelling
https://vimeo.com/191898249
Key Concepts in Computing
https://matthewcomputingblog.wordpress.com/2016/05/26/dice-3010-final-project-home-automation-with-beacons/

Introduction to Digital Cultures
http://jordanmcnairy.weebly.com/body-cameras.html

Dice 3030: http://shawnastewart.weebly.com/network-public-as-catharsis.html
Dice 3000: http://stephenjswisher.weebly.com/digital-spaces.html

**Comment by jfehrenbacher** [comment]
I know I initially wanted to go with Essential Grid, but there are a few little issues that make me think it might not be the direction we want to go, especially considering the fact that we're not going to be working with the LMS within the theme. I can go into more detail on Friday, if need be. Anyway, [here's](http://suncs.staging.wpengine.com/courses-2-2/) the new courses page (the old ones still exist, if we really want to stick with Ess. Grid). The images will not all be the same in the final iteration. This format allows us to have as long of excerpts as we want, not worry about categories or other functionalities we're not interested in, and display whatever other information we want, without having to rely on 3rd party plugins. 

The first DICE course ([DICE 3000 Introduction to Digital Cultures](http://suncs.staging.wpengine.com/dice-3000-introduction-to-digital-cultures/)) is populated with details and course work. Is there any other information we're hoping to add?

**Comment by jfehrenbacher** [comment]
Also, it looks like the Key Concepts in Computing link provided is a private link.

**Comment by reiners** [comment]
Hi Jack,
This looks great! I can't think of additional information to add to the course. Rick and Trish will be going over all content (including course descriptions) before we go live, so this is great for now!
Thanks,
Sara

Sara Reiner | Director of Marketing and Communications
School of New and Continuing Studies | Seattle University

Office: (206) 296-2461
seattleu.edu/ncs


________________________________
