### ISSUE TITLE
Create content for Non-Matric Persona

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#47]
Create content for Non-Matric Persona and, when ready, place it in #46 so Jack can work with it.

**Comment by reiners** [comment]
Here is some starter content. This of course will be more filled out once Rick and Trish have had the opportunity to add edits. One thought though is, it would be great to see a section of our courses that list out the non-matric courses. I know in theory al of our courses are technically non-matric, but it would be great if we could have an easier user experience of cherry picking a few we would like to highlight and market each quarter in an easy to find way. Thoughts or suggestions?
[Persona4.docx](https://github.com/suwebdev/ncs-michigan/files/914503/Persona4.docx)
