### ISSUE TITLE
Build out Persona pages

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#48]
Build slider animations for Persona pages. (Three existing plus one new one.)

**Comment by jfehrenbacher** [comment]
[Get.Where.You.Want.to.Go (1).pdf](https://github.com/suwebdev/ncs-michigan/files/906783/Get.Where.You.Want.to.Go.1.pdf)
[Advance.your.Career.pdf](https://github.com/suwebdev/ncs-michigan/files/906784/Advance.your.Career.pdf)
[Meet.Your.Goals.2.pdf](https://github.com/suwebdev/ncs-michigan/files/906785/Meet.Your.Goals.2.pdf)
