### ISSUE TITLE
Theme design revisions

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#5]
Based on the design proposal from #2 we had a couple of revision requests. These should be worked through and posted up as PDFs like we did before.

* Try replacing SU logo in top nav with a NCS logo of our own design. Use SU logo for link in global nav.
* Try a somewhat larger font for body text and see how it looks.

On program pages:

* Try separating sub-nav and statistics box on program homepage.

**Comment by jfehrenbacher** [comment]
Here are two examples of the Web Dev page, the first without the proposed theme design revisions and the second with. I'll also be looking into adding "School of New and Continuing Studies" text to the logo that lives in the header.

Body text went from 16px to 20px in the new version.

[WebDev1Emerald copy.pdf](https://github.com/suwebdev/ncs-michigan/files/778393/WebDev1Emerald.copy.pdf)
[WebDev2Emerald copy.pdf](https://github.com/suwebdev/ncs-michigan/files/778394/WebDev2Emerald.copy.pdf)

**Comment by shawnr** [comment]
These changes are approved by @reiners and me. The only change request is to add small text on SUNCS logo image to say "School of New and Continuing Studies".
