### ISSUE TITLE
Finalize Persona Content/Images

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#51]
To finalize the Persona content and images let's do the following:

* Make body text on Persona slides larger
* Consult with Sara, Rick, and Trish to review text
* Implement any needed text edits
* Consult with Sara, Rick, and Trish to review images
* Find and implement any replacement images needed

**Comment by reiners** [comment]
Rick and Trish are reviewing the content for the personas now. They would like a call to action at the end of each persona connecting to and calling our our program offerings.

**Comment by jfehrenbacher** [comment]
As persona content is still under review I am holding off on making any changes just yet.
