### ISSUE TITLE
Package content for Info Center for production

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#53]
Package the content into a document that makes it clear which content goes onto which page so that it can be handed off for production.

**Comment by reiners** [comment]
![suki](https://cloud.githubusercontent.com/assets/25487538/25345639/68c209fe-28ca-11e7-92a7-4049e4cd2a38.png)
[Info.Center (2).docx](https://github.com/suwebdev/ncs-michigan/files/952304/Info.Center.2.docx)
[Student Handbook_DRAFT.pdf](https://github.com/suwebdev/ncs-michigan/files/952305/Student.Handbook_DRAFT.pdf)
