### ISSUE TITLE
Get Student Success/Testimonial Content

### ISSUE THREAD

**Issue by jfehrenbacher** [suwebdev/ncs-michigan#58]
Get a blurb for the job placement/student success page as well as student written testimonials, along with images.

**Comment by reiners** [comment]
![kim](https://cloud.githubusercontent.com/assets/25487538/25758864/fa5214dc-3184-11e7-89b1-eb592c6f7eae.jpg)
![tyler](https://cloud.githubusercontent.com/assets/25487538/25758866/fa52c88c-3184-11e7-95df-31d2d59e2124.jpg)
![luke](https://cloud.githubusercontent.com/assets/25487538/25758865/fa521f4a-3184-11e7-8abd-b627835b1320.jpg)
![somountha](https://cloud.githubusercontent.com/assets/25487538/25758867/fa568eb8-3184-11e7-81aa-a07568872bc8.jpg)
[job placement:student success .docx](https://github.com/suwebdev/ncs-michigan/files/979959/job.placement.student.success.docx)
