### ISSUE TITLE
Update Information Center Navigation/Pages

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#61]
* Bring navigation for Information Center in line with IA document.

* Add pages as needed to fill out placeholders for content described in IA document.: https://docs.google.com/document/d/1jX9KiAaHCjkdHV7_2Rt4e_6A26R6FxyNjBpYZLTdW08/

* Make Handbook link in main nav go directly to the PDF (maybe try indicating PDF in the link)

* Update living NCS IA document (linked above) as needed to keep things in sync (work with @reiners to make sure all of that fits)

**Comment by jfehrenbacher** [comment]
Handbook link changed to Handbook (PDF) and now links directly to pdf file.

I just want to make sure you guys saw my remarks in #55. I'm assuming that's what the fourth bullet is in reference to, but I wanted to double check.

**Comment by shawnr** [comment]
Resolved IA updates/ambiguities.

**Comment by jfehrenbacher** [comment]
Here are a few examples of how we could handle the mega menu navigation for the Information Center. The choice essentially comes down to whether we want a paragraph or no paragraph, and also how we want to represent "Apply Now/Request Information/Employment Opportunities" assuming we want all of those options to exist within the mega menu. Let me know what you think.

<img width="1085" alt="screen shot 2017-05-17 at 1 52 14 pm" src="https://cloud.githubusercontent.com/assets/14934268/26176862/74372b08-3b0c-11e7-816b-cf50211aede4.png">
<img width="1085" alt="screen shot 2017-05-17 at 2 01 19 pm" src="https://cloud.githubusercontent.com/assets/14934268/26176861/7436ebf2-3b0c-11e7-8ce2-abd729be2727.png">
<img width="1085" alt="screen shot 2017-05-17 at 2 20 40 pm" src="https://cloud.githubusercontent.com/assets/14934268/26176860/7435549a-3b0c-11e7-80cb-7e4fc3460af8.png">

**Comment by reiners** [comment]
Hi Jack,
Can we try Option 2 but with red buttons like in Option 1, rather than the photo overlay? I think that the red button is more dynamic and attention grabbing. What do you think?
Thanks,
Sara

**Comment by jfehrenbacher** [comment]
Something like this?

<img width="1086" alt="screen shot 2017-05-22 at 3 17 34 pm" src="https://cloud.githubusercontent.com/assets/14934268/26330641/d0f1e3bc-3f01-11e7-9a0c-0da87b0f8b64.png">

**Comment by reiners** [comment]
That looks AWESOME! What do you think? Thanks! :)
Sara


Sara Reiner | Director of Marketing and Communications
School of New and Continuing Studies | Seattle University

Office: (206) 296-2461
seattleu.edu/ncs

________________________________

**Comment by jfehrenbacher** [comment]
Working from the 'Admissions' and 'Info.Center.2' documents
[Info.Center.2.docx](https://github.com/suwebdev/ncs-michigan/files/1027410/Info.Center.2.docx)
[Admissions.docx](https://github.com/suwebdev/ncs-michigan/files/1026759/Admissions.docx)

<br>

**ADMISSIONS**

**Custom Application Form** links [here](https://seattleu.secure.force.com/form?formid=217882)

[**Admissions Requirements**
](http://suncs.staging.wpengine.com/information-center/admissions-requirements/)

<br>

**COST & FINANCIAL AID**

[**Tuition Explained**
](http://suncs.staging.wpengine.com/information-center/tuition-explained/)

I had been planning on using the Pricing Table element within the theme, which would look like this:
<img width="1689" alt="screen shot 2017-05-24 at 12 51 36 pm" src="https://cloud.githubusercontent.com/assets/14934268/26422739/eb10f010-407f-11e7-8818-5d426094976a.png">
But as you can see here:
<img width="1691" alt="screen shot 2017-05-24 at 12 53 42 pm" src="https://cloud.githubusercontent.com/assets/14934268/26422785/0dd21520-4080-11e7-9aec-81cd102f8ca8.png">
It's breaking somewhere along the way. I haven't been able to figure it out, but I have added a third party plugin called "TablePress". It's not as sexy, but it gets the job done:
<img width="1449" alt="screen shot 2017-05-24 at 1 12 24 pm" src="https://cloud.githubusercontent.com/assets/14934268/26423493/b761e780-4082-11e7-8173-ed377ba90719.png">

[**Estimated Costs Per Program**
](http://suncs.staging.wpengine.com/information-center/estimated-costs-per-program/)

This page has a couple more examples of the TablePress plugin.

[**Financial Aid**
](http://suncs.staging.wpengine.com/information-center/financial-aid/)

[**Veterans Benefits**](http://suncs.staging.wpengine.com/information-center/veterans-benefits/)

I'm assuming the Veterans Benefits content from [Admissions.docx](https://github.com/suwebdev/ncs-michigan/files/1027446/Admissions.docx) isn't completely done.

<br>

**STUDENT RESOURCES**

**Time Schedule**

Do we essentially just want all of the content from this document on this page, or is this something else entirely?
[NCS.Time.Schedule.docx](https://github.com/suwebdev/ncs-michigan/files/1027382/NCS.Time.Schedule.docx)

[**Advising Center**](http://suncs.staging.wpengine.com/information-center/tuition-explained-2/)

Do we have special content that we want to live on the Advising Center page, or maybe excerpts about each section of the Advising Center? I kind of feel like they're each pretty self-explanatory.

[**Support Services**](http://suncs.staging.wpengine.com/information-center/support-services/)

Right now this page is just links to the services mentioned in [Info.Center.2.docx](https://github.com/suwebdev/ncs-michigan/files/1027433/Info.Center.2.docx). Images are placeholders. If we want content elaborating on each service that can be added as well.

[**Forms**](http://suncs.staging.wpengine.com/information-center/forms/)

This page is, similarly, a list of links. This one has space for content if we want it for each link, and is how we could handle content for the Support Services page as well if we'd like.

**Policies**

In [Info.Center.2.docx](https://github.com/suwebdev/ncs-michigan/files/1027459/Info.Center.2.docx) there is a list of policies that we felt would be particularly useful for NCS students. This page will probably feel similar to the Forms and Support Services pages in that it will be a bunch of links. Do we want to have descriptions included for each policy link? 


**Index of University Policies**

Was our intention for this to just link straight to [this](https://www.seattleu.edu/redhawk-axis/academic-policies/) seattleu.edu page from the mega menu?


**Transfer Student Information**

No content for this yet, I don't think.

<br>

Note: Sliders are temporary.

I'll be editing this comment as more pages are built out.

**Comment by jfehrenbacher** [comment]
Advising Center Link is incorrect in above comment and edit function is for some reason not working.

Here's the correct link
http://suncs.staging.wpengine.com/information-center/advising-center/
