### ISSUE TITLE
Populate WATS course pages with student work samples

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#62]
Look at issue #54 to see links and descriptions for student course work. Populate course pages with the work samples accordingly.

**Comment by jfehrenbacher** [comment]
Student work samples added to the following:

[WATS Intro To Web Development](http://suncs.staging.wpengine.com/web-development/courses/wats-intro-to-web-development/)

[WATS Intro to Javascript Programming for the Web](http://suncs.staging.wpengine.com/web-development/courses/wats-intro-to-javascript-programming/)

[WATS Building Javascript Applications for the Web](http://suncs.staging.wpengine.com/web-development/courses/wats-building-javascript-applications/)

[WATS User Science and Testing](http://suncs.staging.wpengine.com/web-development/courses/wats-user-science-and-testing/)

[WATS Web Development Capstone](http://suncs.staging.wpengine.com/web-development/courses/wats-web-development-capstone/)

**Comment by shawnr** [comment]
Can you change Luke van der Poel's link to: http://www.lvpoel.me/wats1020-flickr-search/ on the Intro to JS page?
