### ISSUE TITLE
Create Persona Content

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#7]
Write content for each Persona page.

* Get Where You Want to Go (Degree Completion)
* Meet Your Goals (Flexibility)
* Advance Your Career (Professional Development)

**Comment by reiners** [comment]
[Meet Your Goals (2).pdf](https://github.com/suwebdev/ncs-michigan/files/778080/Meet.Your.Goals.2.pdf)
[Get Where You Want to Go.pdf](https://github.com/suwebdev/ncs-michigan/files/778084/Get.Where.You.Want.to.Go.pdf)
[Advance your Career.pdf](https://github.com/suwebdev/ncs-michigan/files/778123/Advance.your.Career.pdf)

**Comment by shawnr** [comment]
Approved by everyone!
