### ISSUE TITLE
Update content per Missing Content doc

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#70]
See attached docx file for content revisions/updates.

[Missing.Content.docx](https://github.com/suwebdev/ncs-michigan/files/997713/Missing.Content.docx)

**Comment by jfehrenbacher** [comment]
Revisions made.

"About" pages now being built with content form this document from Issue #3 
[issue3aboutcontent.docx](https://github.com/suwebdev/ncs-michigan/files/1030166/issue3aboutcontent.docx)

[**Dean's Welcome**](http://suncs.staging.wpengine.com/about/deans-welcome/)

I know we eventually want a video for this, but for now it'll exist like this. And with a picture of Trish as placeholder until we get a decent picture of our Dean.

**[Our Mission](http://suncs.staging.wpengine.com/wp-admin/post.php?vc_action=vc_inline&post_id=694&post_type=page)**

[**Why Choose NCS?**](http://suncs.staging.wpengine.com/about/why-choose-ncs/)

**Comment by jfehrenbacher** [comment]
Also worth mentioning, of the persona titles listed in the Missing.Content.docx document, two are too long to display in the teaser boxes that we are currently using. 

Specifically, the 'Get Where You Want To Go' and 'Just Looking To Take A Class?' sections. This can be viewed on the home page:

http://suncs.staging.wpengine.com/

**Comment by jfehrenbacher** [comment]
Faculty & Staff:

http://suncs.staging.wpengine.com/about/faculty-staff/
