### ISSUE TITLE
Replace Revolution Slider on interior pages

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#71]
Keep Rev Slider where we are making animations (Home, Personas), but remove them where we are just fading in an image. Replace with comparable image/heading combo.

**Comment by jfehrenbacher** [comment]
To create headers that don't utilize Slider Revolution but have the same aesthetic I've taken the following steps:

- Create a row, change its "Row Type" to "Blox"
- Check "Used as Page Title?"
- Check "Full Width Container"
- Add a "Single Image" element to row with a size of 1920x500 that has been stylized accordingly
-  In "Image Size" add "full"
- "Image Alignment", "Center"
- Under the "Design Options" tab, add a left and right margin of "-25px" for mobile compatibility purposes

You'll end up with a page header that looks like this:

<img width="1434" alt="screen shot 2017-05-22 at 3 29 48 pm" src="https://cloud.githubusercontent.com/assets/14934268/26330999/863c7a42-3f03-11e7-8e69-de1451487461.png">

As seen here:
http://suncs.staging.wpengine.com/about/our-mission/

If you see any problems with this method please let me know!

Edit: Removed unnecessary step to change row height to "500".

**Comment by jfehrenbacher** [comment]
Note: Because we have so many sliders made already, and because I'm going to have to create images and then edit each page accordingly, this issue may need to be taken into the next sprint.

**Comment by shawnr** [comment]
Consider other elements that can achieve the goal without having to make an image for each page. We want something that unifies sections, but also gets out of the way of users, and something that allows us to add/change pages without too much fiddling.

**Comment by jfehrenbacher** [comment]
How do we feel about something like this? 

http://suncs.staging.wpengine.com/about/deans-welcome/

It's single image with a height of 400px. Each menu section would have its own image. Does this look alright?
