### ISSUE TITLE
Gather Time Schedule Information

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#77]
Consult with Elizabeth to get a complete time schedule of scheduled courses for AY17-18.

Attach spreadsheet of course sections to #76 so time schedule page can be built.

**Comment by reiners** [comment]
[Copy of NCS 17-18 Course Schedule 5_16_17(1).xlsx](https://github.com/suwebdev/ncs-michigan/files/1042310/Copy.of.NCS.17-18.Course.Schedule.5_16_17.1.xlsx)

**Comment by shawnr** [comment]
Updated on issue #86 to fill in info.
