### ISSUE TITLE
Investigate Design Treatments for Multimedia

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#8]
We want to discover what's available for Multimedia playback.

**Comment by jfehrenbacher** [comment]
As far as video playback goes, the Michigan Theme gives us access to a basic video player that links to any Youtube or Vimeo link and plays on the page, as well as a "Video Play Button" that is, essentially, a clickable icon that opens a modal video window.

The button, I'm sure, could be styled with an image background to look like a video player, so it's essentially just the difference between modal and non-modal playback.

Revolution Slider also has support for video backgrounds, as we've talked about. I've looked at a lot of examples and tutorials using it, and it seems like it can be a little sketchy (not loading quickly, choppy when it does load, often a questionable design choice even when it does work, etc.)

There are also myriad free video plugins that allow for video galleries, which could be useful if we wanted something like access to other videos from our YouTube channels, or something to that effect.

As far as audio goes, the Michigan Theme, as far as I can tell, has no extra functionality for embedding audio outside of what Wordpress already offers. If we wanted to get fancier with it, there are plenty of free or cheap plugins.

[Soundcloud Is Gold](https://wordpress.org/plugins/soundcloud-is-gold/) would be great if we started building out an NCS SoundCloud.

[HTML5 jQuery Audio Player](https://wordpress.org/plugins/html5-jquery-audio-player/) is a basic mp3 and ogg audio player. Its most appealing feature is that it looks really slick, and would be more useful if we needed to make playlists. There's a paid version, but it just seems to add a bunch of functionality that we wouldn't need.

[Compact WP Audio Player](https://wordpress.org/plugins/compact-wp-audio-player/) is exactly that. A few different themes, but mostly just a play button and a timeline.

There are always more options out there, and if there's anything that I didn't address here let me know!
