### ISSUE TITLE
Settle Policies Pages

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#80]
* Under Admissions, Policies page should list Admissions-specific policies (leave Lorem Ipsum in the introduction of the page) and should then refer students to larger college/university policies page under student resources.

* Under Student Resources, Policies page highlights NCS College Policies, relevant University policies, and then links to main University policy page.

Leave Lorem Ipsum text for anywhere it seems like we need an introduction or explanation and don't yet have one.

**Comment by jfehrenbacher** [comment]
Here's a basic Student Resources - Policies page, with the relevant policies, as dictated by the 
[Info.Center.2.docx](https://github.com/suwebdev/ncs-michigan/files/1061941/Info.Center.2.docx) document, with a link to the Redhawk Axis index of university policies. 

I was also wondering what policies are considered 'Admissions-specific', for the Admissions Policies page?

http://suncs.staging.wpengine.com/information-center/college-policies/

**Comment by shawnr** [comment]
@Trish1 Can we figure out which of these are admissions-specific? Just add a note here and @jfehrenbacher will add them in.

**Comment by dasein56** [comment]
[2 Admission Policies links[1].docx](https://github.com/suwebdev/ncs-michigan/files/1132174/2.Admission.Policies.links.1.docx)
