### ISSUE TITLE
Content for Transfer Student Information page

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#81]
Generate content for Transfer Student Information. Attach content docs here.

**Comment by reiners** [comment]
[TRANSFER_BROCHURE_FINAL.pdf](https://github.com/suwebdev/ncs-michigan/files/1039671/TRANSFER_BROCHURE_FINAL.pdf)

**Comment by jfehrenbacher** [comment]
http://suncs.staging.wpengine.com/information-center/transfer-student-information/
