### ISSUE TITLE
Generate content for Veteran's Financial Info.

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#82]
Need to create content to speak to the veteran's community about benefits and how NCS fits into that. http://suncs.staging.wpengine.com/information-center/veterans-benefits/

**Comment by reiners** [comment]
[TRANSFER_BROCHURE_FINAL.pdf](https://github.com/suwebdev/ncs-michigan/files/1039664/TRANSFER_BROCHURE_FINAL.pdf)

**Comment by reiners** [comment]
[Veterans Benefits.docx](https://github.com/suwebdev/ncs-michigan/files/1048663/Veterans.Benefits.docx)
