### ISSUE TITLE
Populate new content on Veteran's Benefits page

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#87]
[Veterans.Benefits.docx](https://github.com/suwebdev/ncs-michigan/files/1065038/Veterans.Benefits.docx)

Add attached content to the Veteran's Benefits page (replace current content).

**Comment by jfehrenbacher** [comment]
http://suncs.staging.wpengine.com/information-center/veterans-benefits/

**Comment by jfehrenbacher** [comment]
Edit headers before closing issue
