### ISSUE TITLE
Update contact info

### ISSUE THREAD

**Issue by shawnr** [suwebdev/ncs-michigan#97]
1. Remove `ncs@seattleu.edu` email address
2. Remove fax number
3. Update address in top bar
4. Update address in footer

Footer and top bar address should be:

SU Law School Annex (LSAX)
1215 E. Columbia St. Rm 141
Seattle, WA 98122

Populate about us page with:
  1. Mailing address clearly labelled
  3. Embedded map
  4. Driving directions
  5. NCS Admissions contact info (email, Tyler's phone number)
  6. Parking info

**Comment by reiners** [comment]
[Contact Us.docx](https://github.com/suwebdev/ncs-michigan/files/1109609/Contact.Us.docx)

**Comment by jfehrenbacher** [comment]
Removed ncs@seattleu.edu
Removed fax number
Updated address in top bar with the following

**"1215 E. Columbia St., LSAX 141
Seattle, WA 98122"**

Updated footer with the following:

**SU Law School Annex (LSAX)
1215 E. Columbia St. Rm 141
Seattle, WA 98122**

Pushed and committed footer.php.

I do think we should discuss how the contact information in the header looks, and possible solutions to make it look more natural.

I'm a little unclear as to whether we want to populate the 'About Us' landing page with the information given above, or the 'About Us' --> 'Contact Us' page.

**Comment by shawnr** [comment]
Investigate linking phone, email, & address.

Make them all one line. Or add labels to phone and email to make those both two lines.
